# Generated by Django 3.0.6 on 2020-08-03 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
